force-app/main/default/objects/Sentiment_Map_Aggregate__mdt/Sentiment_Map_Aggregate__mdt.object-meta.xml
<CustomObject>
    <label>Sentiment Map Aggregate</label>
    <pluralLabel>Sentiment Map Aggregates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sentiment_Map_Aggregate__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KPI</fullName>
                <default>true</default>
                <label>KPI</label>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Map_Aggregate__mdt/fields/Legend_Theme__c.field-meta.xml
<CustomField>
    <fullName>Legend_Theme__c</fullName>
    <label>Legend Theme</label>
    <referenceTo>Legend_Theme__mdt</referenceTo>
    <relationshipLabel>Sentiment Map Aggregates</relationshipLabel>
    <relationshipName>sentiment_map_Aggregates</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Sentiment_Map_Aggregate__mdt/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentiment_Map_Settings__mdt/Sentiment_Map_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Sentiment Map Settings</label>
    <pluralLabel>Sentiment Map Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sentiment_Map_Settings__mdt/fields/Default_Map_Region__c.field-meta.xml
<CustomField>
    <fullName>Default_Map_Region__c</fullName>
    <label>Default Map Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>World</fullName>
                <default>true</default>
                <label>World</label>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Map_Settings__mdt/fields/Enable_Sentiment_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Enable_Sentiment_Analysis__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Sentiment Analysis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SettingsService.cls
public class SettingsService  {
	@AuraEnabled
	sentiment_map_Settings__mdt Settings{ get; set; }
	@AuraEnabled
	public Boolean SentimentAnalysisEnabled { get; set; }

	@AuraEnabled
	public Map<String, sentiment_map_Aggregate__mdt> Aggregates { get; set; }
	@AuraEnabled
	public List<sentiment_map_Aggregate__mdt> SortedAggregates { get; set; }
		
	@AuraEnabled
	public Map<String, sentiment_map_Aggregate__mdt> RegionAggregates { get; set; }
	@AuraEnabled
	public List<sentiment_map_Aggregate__mdt> SortedRegionAggregates { get; set; }

	@AuraEnabled
	public Map<String, sentiment_map_Aggregate__mdt> KPIAggregates { get; set; }
	@AuraEnabled
	public List<sentiment_map_Aggregate__mdt> SortedKPIAggregates { get; set; }

	public SettingsService() {
		List<sentiment_map_Settings__mdt> lSettings;

		lSettings = [SELECT Id, DeveloperName, Default_Map_Region__c, Enable_Sentiment_Analysis__c
					   FROM sentiment_map_Settings__mdt];

		if(lSettings.size() > 0) {
			 Settings = lSettings[0];

			 if(Test.isRunningTest()) SentimentAnalysisEnabled = true;
			 else SentimentAnalysisEnabled = Settings.Enable_Sentiment_Analysis__c;
		}	

		this.setAggregates();
	}

	private void setAggregates() {
		RegionAggregates = new Map<String, sentiment_map_Aggregate__mdt>();
		SortedRegionAggregates = new List<sentiment_map_Aggregate__mdt>();
		KPIAggregates = new Map<String, sentiment_map_Aggregate__mdt>();
		SortedKPIAggregates = new List<sentiment_map_Aggregate__mdt>();
		Aggregates = new Map<String, sentiment_map_Aggregate__mdt>();
		SortedAggregates = [SELECT DeveloperName, MasterLabel, Category__c,
							Default__c, Field_Name__c,
							Legend_Theme__c, Object_Name__c,
							Rank__c
							FROM sentiment_map_Aggregate__mdt
							ORDER BY Rank__c];
		for(sentiment_map_Aggregate__mdt aggregate: SortedAggregates) {
			if('Region' == aggregate.Category__c) {
				RegionAggregates.put(aggregate.MasterLabel, aggregate);
				SortedRegionAggregates.add(aggregate);
			}

			if('KPI' == aggregate.Category__c) {
				KPIAggregates.put(aggregate.MasterLabel, aggregate);
				SortedKPIAggregates.add(aggregate);
			}

			Aggregates.put(aggregate.MasterLabel, aggregate);
		}
	}
}